/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0d0d18",
        "inverse-on-surface": "#2f2f3c",
        "on-primary": "#3f008e",
        "on-surface-variant": "#ccc3d8",
        "on-error-container": "#ffdad6",
        "primary-container": "#7c3aed",
        "primary": "#d2bbff",
        "outline": "#958da1",
        "surface-container": "#1e1e2b",
        "surface-variant": "#343440",
        "on-secondary-fixed": "#1b1b23",
        "tertiary-fixed-dim": "#ffb784",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-container": "#494851",
        "error-container": "#93000a",
        "outline-variant": "#4a4455",
        "on-secondary-container": "#b9b7c2",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "inverse-primary": "#732ee4",
        "on-secondary": "#303038",
        "on-secondary-fixed-variant": "#46464f",
        "on-background": "#e3e0f1",
        "on-tertiary-fixed-variant": "#713700",
        "on-tertiary-container": "#ffe0cd",
        "surface-container-highest": "#343440",
        "on-primary-fixed": "#25005a",
        "on-tertiary-fixed": "#301400",
        "surface": "#12121e",
        "on-surface": "#e3e0f1",
        "primary-fixed-dim": "#d2bbff",
        "secondary-fixed-dim": "#c7c5d0",
        "background": "#12121e",
        "surface-dim": "#12121e",
        "secondary": "#c7c5d0",
        "on-tertiary": "#4f2500",
        "tertiary-fixed": "#ffdcc6",
        "secondary-fixed": "#e4e1ec",
        "primary-fixed": "#eaddff",
        "inverse-surface": "#e3e0f1",
        "surface-container-high": "#292935",
        "surface-bright": "#383845",
        "surface-tint": "#d2bbff",
        "surface-container-low": "#1a1a26",
        "tertiary": "#ffb784",
        "tertiary-container": "#a15100",
      },
      fontFamily: {
        "hanken": ["Hanken Grotesk", "sans-serif"],
        "geist": ["Geist", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "code": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
export default config
