"use client"
import { useState } from "react"
import { getMoodSummary } from "@/lib/api"

interface SummaryData {
  summary: string
  generated_at: string
  days: number
  tracks_analyzed: number
}

export default function MoodSummary({ initialDays = 7 }: { initialDays?: number }) {
  const [data, setData] = useState<SummaryData | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [days, setDays] = useState(initialDays)

  async function generate(d = days) {
    setLoading(true); setError(null)
    try {
      setData(await getMoodSummary(d))
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : "Could not generate summary."
      setError(msg.includes("503") ? "Add your Anthropic API key to backend/.env" : msg)
    } finally { setLoading(false) }
  }

  return (
    <div className="bg-white dark:bg-[#111118] border border-slate-200 dark:border-[#1e1e2a] rounded-2xl p-6 shadow-sm">
      <div className="flex items-start justify-between gap-4 mb-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-2 h-2 rounded-full bg-violet-500" />
            <h2 className="font-semibold text-lg text-slate-900 dark:text-slate-100">AI Mood Summary</h2>
          </div>
          <p className="text-sm text-slate-400 dark:text-slate-500">Claude analyses your listening patterns</p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <select
            value={days}
            onChange={(e) => setDays(Number(e.target.value))}
            className="bg-slate-50 dark:bg-[#1a1a22] border border-slate-200 dark:border-[#2a2a38] text-sm rounded-lg px-2 py-1.5 outline-none text-slate-700 dark:text-slate-300"
          >
            <option value={7}>Last 7 days</option>
            <option value={14}>Last 14 days</option>
            <option value={30}>Last 30 days</option>
            <option value={90}>Last 3 months</option>
            <option value={365}>All time</option>
          </select>
          <button
            onClick={() => generate(days)} disabled={loading}
            className="flex items-center gap-1.5 bg-violet-600 hover:bg-violet-700 disabled:opacity-50 text-white text-sm font-medium px-3 py-1.5 rounded-lg transition-colors whitespace-nowrap shadow-sm"
          >
            {loading
              ? <div className="w-3.5 h-3.5 border-2 border-white/40 border-t-white rounded-full animate-spin" />
              : <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}><path d="M12 2a10 10 0 1 0 10 10" strokeLinecap="round" /><path d="M22 2 12 12M22 2h-6M22 2v6" strokeLinecap="round" strokeLinejoin="round" /></svg>
            }
            {loading ? "Thinking..." : data ? "Regenerate" : "Generate"}
          </button>
        </div>
      </div>

      {error && (
        <div className="text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800/50 rounded-xl px-4 py-3">
          {error}
        </div>
      )}

      {!data && !error && !loading && (
        <div className="flex flex-col items-center justify-center py-8 text-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-violet-50 dark:bg-violet-950/30 border border-violet-100 dark:border-violet-800/50 flex items-center justify-center text-2xl">
            🧠
          </div>
          <p className="text-sm text-slate-400 dark:text-slate-500 max-w-xs">
            Hit Generate and Claude will write a personal mood narrative based on your listening history.
          </p>
        </div>
      )}

      {loading && (
        <div className="flex items-center gap-3 py-8 justify-center text-slate-400 text-sm">
          <div className="w-4 h-4 border-2 border-violet-200 border-t-violet-500 rounded-full animate-spin" />
          Claude is reading your vibes...
        </div>
      )}

      {data && !loading && (
        <div className="space-y-3">
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-[15px]">{data.summary}</p>
          <div className="flex items-center justify-between pt-2 border-t border-slate-100 dark:border-[#1e1e2a]">
            <span className="text-xs text-slate-400 dark:text-slate-500">
              {data.tracks_analyzed} tracks · {data.days}d window
            </span>
            <span className="text-xs text-slate-400 dark:text-slate-500">Generated by Claude</span>
          </div>
        </div>
      )}
    </div>
  )
}
